name: iOS Build Clean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup CocoaPods via Homebrew
      run: |
        brew update
        brew install cocoapods
        pod --version
      
    - name: Setup iOS dependencies
      run: |
        cd ios
        rm -rf Pods Podfile.lock
        pod repo update
        pod install --verbose
      
    - name: Clean and setup iOS
      run: |
        flutter clean
        flutter pub get
        cd ios
        pod install
      
    - name: Build iOS Simulator
      run: flutter build ios --debug --simulator
      
    - name: Build IPA (Simulator)
      run: flutter build ipa --debug --simulator
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: build/ios/ipa/
        retention-days: 30
