name: iOS Build Clean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.1'
        
    - name: Install dependencies
      run: flutter pub get

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install CocoaPods (gem)
      env:
        GIT_TERMINAL_PROMPT: 0
      run: |
        gem install cocoapods -v 1.15.2 --no-document
        pod --version
      
    - name: Setup iOS dependencies (use CDN)
      env:
        COCOAPODS_DISABLE_STATS: 'true'
        GIT_TERMINAL_PROMPT: 0
      run: |
        set -euo pipefail
        cd ios
        rm -rf Pods Podfile.lock
        # Capture full output to a log and show the tail on failure
        (pod install --repo-update --verbose 2>&1 | tee pod_install.log) || {
          echo "\n===== pod install last 80 lines =====";
          tail -n 80 pod_install.log || true;
          exit 1;
        }
      
    - name: Clean and setup iOS
      run: |
        flutter clean
        flutter pub get
        cd ios
        pod install
      
    - name: Build iOS Simulator app
      run: flutter build ios --debug --simulator
      
    - name: Upload simulator app artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-simulator-app
        path: build/ios/iphonesimulator/
        retention-days: 30
